# Timeout for commands executed by starship (ms)
command_timeout = 1000

# add_newline = false
# A minimal left prompt
# format = """$directory$character$git_branch$docker_context"""
# move the rest of the prompt to the right
right_format = """$gcloud"""

#[angular]
#symbol = "󰚲 "

[aws]
symbol = "  "
style = 'bold blue'
format = 'on [$symbol($profile )(\($region\) )]($style)'


[azure]
symbol = " "

[battery]
full_symbol = '🔋 '
charging_symbol = '󰚥 '
discharging_symbol = '󱟩 '

[[battery.display]]
threshold = 10
style = 'bold red'

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "
# disabled = true

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "
style = 'bold cyan'
# format = '[$symbol ]($style)'

[gcloud]
symbol = "󰊭"
# symbol = " "
format = '[$symbol $account(\($project\))]($style) '
style = "bold green"

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

#[jenkins]
#symbol = " "

[julia]
symbol = " "

[kubernetes]
symbol = "☸ "
disabled = true
detect_files = ['Dockerfile']
format = '[$context(\[$namespace\])]($style) '

[lua]
symbol = " "

#[markdown]
#symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

#[npm]
#symbol = "󰛷 "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
#KaliLinux = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = " "

[pijul_channel]
symbol = "🪺 "

#[postgres]
#symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

#[react]
#symbol = " "

[scala]
symbol = " "

#[soundcloud]
#symbol = " "

[spack]
symbol = "🅢 "

#[spotify]
#symbol = " "

[swift]
symbol = "󰛥 "

[terraform]
symbol = " "
#[vim]
#symbol = " "

#[vue]
#symbol = "󰡄 "

#[webpack]
#symbol = "󰜫 "

[character]
#  bolder arrow
success_symbol = '[→](bold green) '
error_symbol = '[✗](bold red) '
